# Generated by Django 5.0.4 on 2024-05-20 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to='Events/images/', verbose_name='تصویر')),
                ('event_url', models.URLField(verbose_name='لینک')),
                ('event_date', models.DateField(verbose_name='تاریخ')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'اتفاق',
                'verbose_name_plural': 'اتفاقات',
                'ordering': ['event_date'],
            },
        ),
        migrations.CreateModel(
            name='EventDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to='Events/Desciption/images/', verbose_name='تصویر')),
                ('video', models.FileField(upload_to='Events/Desciption/video/', verbose_name='ویدیو')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_description', to='events.event', verbose_name='اتفاق')),
            ],
            options={
                'verbose_name': 'توضیح اتفاق',
                'verbose_name_plural': 'توضیحات اتفاق',
            },
        ),
    ]
