# Generated by Django 5.0.4 on 2024-04-28 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0001_initial'),
        ('musices', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='musices_genre', to='genres.genre', verbose_name='ژانر'),
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
