# Generated by Django 5.0.4 on 2024-04-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musices', '0003_alter_music_genre_delete_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='plays',
            field=models.IntegerField(default=0, verbose_name='بلی'),
        ),
    ]
