# Generated by Django 5.0.4 on 2024-04-30 13:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musices', '0004_music_plays'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='Composer',
            new_name='composer',
        ),
        migrations.RenameField(
            model_name='music',
            old_name='Regulators',
            new_name='regulators',
        ),
        migrations.RenameField(
            model_name='music',
            old_name='Songwriter',
            new_name='songwriter',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='title',
        ),
        migrations.AddField(
            model_name='comment',
            name='score',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز'),
        ),
    ]
