# Generated by Django 5.0.4 on 2024-05-15 06:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_otp_token_alter_otp_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResetPasswordOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.IntegerField(verbose_name='کد otp')),
                ('token', models.CharField(max_length=100, unique=True, verbose_name='توکن')),
                ('email', models.EmailField(max_length=255, validators=[django.core.validators.EmailValidator], verbose_name='ایمیل')),
            ],
            options={
                'verbose_name': 'کد اعتبار سنجی رمزعبور',
                'verbose_name_plural': 'کد های اعتبار سنجی رمزعبور',
            },
        ),
    ]
