# Generated by Django 5.0.4 on 2024-05-01 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Albom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان آلبوم')),
                ('slug', models.SlugField(max_length=200, verbose_name='اسلاگ آلبوم')),
                ('singer', models.CharField(max_length=100, verbose_name='خواننده')),
                ('image', models.ImageField(upload_to='alboms/files/images/', verbose_name='تصویر آلبوم')),
                ('banner', models.ImageField(upload_to='alboms/files/banners/', verbose_name='تصویر آلبوم')),
                ('release_date', models.DateField(verbose_name='تاریخ اکران')),
                ('likes', models.IntegerField(verbose_name='تعداد لایک ها')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'آلبوم',
                'verbose_name_plural': 'آلبوم ها',
                'ordering': ['release_date', 'created'],
            },
        ),
        migrations.CreateModel(
            name='MusicAlbom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AlbomComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('text', models.TextField(verbose_name='متن')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('albome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albome_comments', to='alboms.albom', verbose_name='آلبوم')),
            ],
            options={
                'verbose_name': 'نظر آلبوم',
                'verbose_name_plural': 'نظرات آلبوم',
                'ordering': ['created'],
            },
        ),
    ]
