# Generated by Django 5.0.4 on 2024-05-01 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alboms', '0001_initial'),
        ('musices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='albomcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_albome_comments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AddField(
            model_name='musicalbom',
            name='albome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albom_musics', to='alboms.albom', verbose_name='آلبوم'),
        ),
        migrations.AddField(
            model_name='musicalbom',
            name='music',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albom_musics', to='musices.music', verbose_name='موزیک های آلبوم'),
        ),
    ]
