# Generated by Django 5.0.4 on 2024-04-25 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alboms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbomComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('text', models.TextField(verbose_name='متن')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('albome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albome_comments', to='alboms.albom', verbose_name='موزیک')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_albome_comments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نظر آلبوم',
                'verbose_name_plural': 'نظرات آلبوم',
                'ordering': ['created'],
            },
        ),
    ]
