# Generated by Django 5.0.4 on 2024-04-25 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alboms', '0002_albomcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albomcomment',
            name='albome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albome_comments', to='alboms.albom', verbose_name='آلبوم'),
        ),
    ]
