# Generated by Django 5.0.4 on 2024-05-02 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alboms', '0003_comment_commentreply_delete_albomcomment'),
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='albom',
            name='genre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='albome_genre', to='genres.genre', verbose_name='ژانر'),
            preserve_default=False,
        ),
    ]
