# Generated by Django 5.0.4 on 2024-05-06 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfavorite',
            name='slug',
        ),
    ]
