# Generated by Django 5.0.4 on 2024-05-06 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0002_remove_userfavorite_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermusicfaver',
            options={'ordering': ['updated'], 'verbose_name': 'علاقمندی موزیک های کاربر', 'verbose_name_plural': 'علاقمندی موزیک های کاربران'},
        ),
        migrations.RemoveField(
            model_name='usermusicfaver',
            name='is_faver',
        ),
    ]
