# Generated by Django 5.0.4 on 2024-05-08 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alboms', '0001_initial'),
        ('favorites', '0004_alter_useralbomefaver_options_and_more'),
        ('musices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfavorite',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usermusicfaver',
            name='user_favorite',
        ),
        migrations.RemoveField(
            model_name='usermusicfaver',
            name='music',
        ),
        migrations.CreateModel(
            name='UserAlbumFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('albume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albome_faver', to='alboms.albom', verbose_name='آلبوم')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums_faver', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'علاقمندی آلبوم های کاربر',
                'verbose_name_plural': 'علاقمندی آلبوم های کاربران',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='UserMusicFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_faver', to='musices.music', verbose_name='آهنگ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='musices_faver', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'علاقمندی موزیک های کاربر',
                'verbose_name_plural': 'علاقمندی موزیک های کاربران',
                'ordering': ['created'],
            },
        ),
        migrations.DeleteModel(
            name='UserAlbomeFaver',
        ),
        migrations.DeleteModel(
            name='UserFavorite',
        ),
        migrations.DeleteModel(
            name='UserMusicFaver',
        ),
    ]
