# Generated by Django 5.0.4 on 2024-05-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='full_name',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='commen_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='نام نمایشی'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='f_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='نام'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='l_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='نام خانوادگی'),
        ),
    ]
