# Generated by Django 5.0.4 on 2024-05-01 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alboms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='اسلاگ')),
                ('count', models.IntegerField(default=0, verbose_name='تعداد علاقه مندی ها')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'علاقمندی های کاربر',
                'verbose_name_plural': 'علاقه مندی های کاربران',
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='UserMusicFaver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_faver', models.BooleanField(default=False, verbose_name='علاقه دارد؟')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'علاقمندی موزیک های کاربر',
                'verbose_name_plural': 'علاقمندی موزیک های کاربران',
                'ordering': ['is_faver', 'updated'],
            },
        ),
        migrations.CreateModel(
            name='UserAlbomeFaver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_faver', models.BooleanField(default=False, verbose_name='علاقه دارد؟')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('albome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albome_faver', to='alboms.albom', verbose_name='آلبوم')),
            ],
            options={
                'verbose_name': 'علاقمندی آلبوم های کاربر',
                'verbose_name_plural': 'علاقمندی آلبوم های کاربران',
                'ordering': ['is_faver', 'updated'],
            },
        ),
    ]
