# Generated by Django 5.0.4 on 2024-05-01 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('favorites', '0001_initial'),
        ('musices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userfavorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favorites', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AddField(
            model_name='useralbomefaver',
            name='user_favorite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_albome_faver', to='favorites.userfavorite', verbose_name='علاقمندی های کاربر'),
        ),
        migrations.AddField(
            model_name='usermusicfaver',
            name='music',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_faver', to='musices.music', verbose_name='آهنگ'),
        ),
        migrations.AddField(
            model_name='usermusicfaver',
            name='user_favorite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_music_faver', to='favorites.userfavorite', verbose_name='علاقمندی های کاربر'),
        ),
    ]
