# Generated by Django 5.0.4 on 2024-04-26 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0001_initial'),
        ('musices', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermusicfaver',
            name='music',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_faver', to='musices.music', verbose_name='آلبوم'),
        ),
    ]
