# Generated by Django 5.0.4 on 2024-04-26 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0003_alter_usermusicfaver_music'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useralbomefaver',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usermusicfaver',
            name='user',
        ),
    ]
