# Generated by Django 5.0.4 on 2024-05-02 20:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genres', '0001_initial'),
        ('musices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Albom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان آلبوم')),
                ('slug', models.SlugField(max_length=200, verbose_name='اسلاگ آلبوم')),
                ('singer', models.CharField(max_length=100, verbose_name='خواننده')),
                ('image', models.ImageField(upload_to='alboms/files/images/', verbose_name='تصویر آلبوم')),
                ('banner', models.ImageField(upload_to='alboms/files/banners/', verbose_name='تصویر آلبوم')),
                ('release_date', models.DateField(verbose_name='تاریخ اکران')),
                ('likes', models.IntegerField(verbose_name='تعداد لایک ها')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albome_genre', to='genres.genre', verbose_name='ژانر')),
            ],
            options={
                'verbose_name': 'آلبوم',
                'verbose_name_plural': 'آلبوم ها',
                'ordering': ['release_date', 'created'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('text', models.TextField(verbose_name='متن')),
                ('score', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('albome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albome_comments', to='alboms.albom', verbose_name='آلبوم')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_albome_comments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نظر آلبوم',
                'verbose_name_plural': 'نظرات آلبوم',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='CommentReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField(verbose_name='پاسخ')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albome_comment_replies', to='alboms.comment', verbose_name='نظر')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_albome_replies', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پاسخ',
                'verbose_name_plural': 'پاسخ ها',
            },
        ),
        migrations.CreateModel(
            name='MusicAlbom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('albome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albom_musics', to='alboms.albom', verbose_name='آلبوم')),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albom_musics', to='musices.music', verbose_name='موزیک های آلبوم')),
            ],
        ),
    ]
