# Generated by Django 5.0.4 on 2024-05-04 09:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('email', models.EmailField(max_length=255, validators=[django.core.validators.EmailValidator], verbose_name='ایمیل')),
                ('username', models.CharField(max_length=255, verbose_name='نام کاربری')),
                ('password', models.CharField(max_length=255, verbose_name='رمز عبور')),
                ('otp_code', models.IntegerField(verbose_name='کد otp')),
                ('id', models.CharField(max_length=500, primary_key=True, serialize=False, unique=True, verbose_name='آیدی')),
            ],
            options={
                'verbose_name': 'کد اعتبارسنجی',
                'verbose_name_plural': 'کدهای اعتبارسنجی',
            },
        ),
    ]
